Beginning to add lame documentation
hyoo-ru/mam_mol pull request #504
Opened 2022-11-13 17:08 UTC by koplenov

2022-11-13 21:01 UTC, koplenov commented
Что подправить?

2022-11-14 03:57 UTC, nin-jin requested changes
Я поправил тексты по мелочи. В остальном всё норм. Разве что я бы поправил демку на что-то более реалистичное. Можно глянуть на opt.js.hyoo.ru как используется $mol_follower.

2022-11-14 03:57 UTC, nin-jin commented on follower/demo/demo.view.tree
> +			Sub <= Follower_sample_content $mol_icon_flash
Странная демка. Кнопка с иконкой делается проще. Тут по хорошему надо показывать как один компонент следует за другим, который постоянно меняет свою позицию.

2022-11-14 06:11 UTC, koplenov commented on follower/demo/demo.view.tree
> +			Sub <= Follower_sample_content $mol_icon_flash
я думал сделать слежение за курсором мыши, но схожу не нашел такого модуля

насчёт постоянно меняющегося:
возможно стоит попробовать сделать демку с mol_plot

какие компоненты у нас ещё динамичны?

2022-11-14 14:46 UTC, nin-jin commented on follower/demo/demo.view.tree
> +			Sub <= Follower_sample_content $mol_icon_flash
Оно следит именно за компонентом. Например, за словом в тексте.

2022-11-25 06:59 UTC, nin-jin commented on follower/demo/demo.view.tree
> +			Sub <= Follower_sample_content $mol_icon_flash
Давай может смёржим пока без этой демки?

2022-11-25 07:17 UTC, koplenov commented on follower/demo/demo.view.tree
> +			Sub <= Follower_sample_content $mol_icon_flash
Поддерживаю

Я по ходу дела в чем буду разбираться - буду накидывать новое

2022-11-25 10:46 UTC, nin-jin commented on follower/demo/demo.view.tree
> +			Sub <= Follower_sample_content $mol_icon_flash
Удалишь эту демку из реквеста?

2022-11-25 14:32 UTC, koplenov commented on follower/demo/demo.view.tree
> +			Sub <= Follower_sample_content $mol_icon_flash
Есть

2022-11-26 05:36 UTC, nin-jin approved these changes

2022-11-26 05:36 UTC, merged