$mol_number
hyoo-ru/mam_mol pull request #529
Opened 2023-02-23 11:39 UTC by wmakeev

- add `min_value` and `max_value` options
- fix precision display
- more detailed demo

2023-02-23 11:59 UTC, nin-jin requested changes

2023-02-23 11:59 UTC, nin-jin commented on number/demo/demo.view.css.ts
> +			width: rem( 17 )
А почему потребовалось так сильно растягивать?

2023-02-23 11:59 UTC, nin-jin commented on number/demo/demo.view.tree
> +		- <= Scroll $mol_scroll sub /
Похоже на артефакт.

2023-02-23 11:59 UTC, nin-jin commented on number/number.view.tree
> +	min_value +NaN
Давай переименуем в value_min и value_max, чтобы value выступало неймспейсом для всех релевантных только ему каналов?

2023-02-23 11:59 UTC, nin-jin commented on number/number.view.tree
> +			enabled <= string_enabled <= enabled -
Минусы ужа давно не обязательно ставить, если что.

2023-02-23 11:59 UTC, nin-jin commented on number/number.view.ts
> +		}
Для этого есть простой паттерн: `Math.min( Math.max( min,  val ), max )`

2023-02-23 11:59 UTC, nin-jin commented on number/number.view.ts
> +			)
Лучше эту логику перенести в value_limited и везде менять значение через него. А то сейчас тут копипаста, а вручную можно задать значение вне лимита.

2023-02-23 11:59 UTC, nin-jin commented on number/number.view.ts
> +			)
Эту логику можно упростить до `!( val < min )`.

2023-02-25 13:31 UTC, wmakeev commented on number/demo/demo.view.css.ts
> +			width: rem( 17 )
Запутался в разметке. Обернул в $mol_row убрал стили.

2023-02-25 13:43 UTC, wmakeev commented on number/number.view.ts
> +		}
Так ведь всё равно придется проверять `min`, `max`, `val` на `null` и `NaN`...

2023-02-25 14:50 UTC, nin-jin commented on number/number.view.ts
> +		}
А зачем тут NaN? По дефолту лучше иметь плюс-минус бесконечность.

2023-02-25 15:11 UTC, nin-jin commented on number/number.view.ts
> +				!( ( this.value() || 0 ) <= this.value_min() )
При NaN тут будет разное поведение в зависимости от положительности минимума. Почему бы не убрать дефолтный 0?

2023-02-25 15:16 UTC, nin-jin commented on number/number.view.ts
> +		}
Я имел ввиду другой подход: `value_liited( val: number ): number`
Ты в него передаёшь новое любое значение, а он пишет уже лимитированное по диапазону. И не надо везде дёргать проверку `value_in_range`.
Или эт не прокатило?

2023-02-25 15:16 UTC, nin-jin approved these changes

2023-02-25 17:10 UTC, wmakeev commented on number/number.view.ts
> +				!( ( this.value() || 0 ) <= this.value_min() )
Я исходил из того, что если значение не указано, то можно считать что оно равно 0, тогда если задан минимум 0 (частый случай), то кнопка декремента будет заблокирована на пустом поле.

2023-02-26 15:12 UTC, nin-jin commented on number/number.view.ts
> +				!( ( this.value() || 0 ) <= this.value_min() )
А если минимум -1, то кнопка тоже будет заблокирована.

2023-02-26 15:16 UTC, nin-jin approved these changes

2023-02-27 08:39 UTC, wmakeev commented on number/number.view.ts
> +				!( ( this.value() || 0 ) <= this.value_min() )
Почему? Нет. А у тебя нет где-то тестового деплоя чтобы проверить? Я там [добавил кейсов](https://i.imgur.com/IWM4j7L.png) для разных диапазонов.

2023-02-27 13:56 UTC, nin-jin commented on number/number.view.ts
> +				!( ( this.value() || 0 ) <= this.value_min() )
Нету. Вот [смотри](https://eval.js.hyoo.ru/#!code=const%20checkMin%20%3D%20%28%20val%2C%20min%20%29%3D%3E%20!%28%20%28%20val%20%7C%7C%200%20%29%20%3C%3D%20min%20%29%0Aconst%20checkMax%20%3D%20%28%20val%2C%20max%20%29%3D%3E%20!%28%20%28%20val%20%7C%7C%200%20%29%20%3E%3D%20max%20%29%0A%0Aconst%20negativeMin%20%3D%20checkMin%28%20NaN%2C%20-10%20%29%20%2F%2F%20enabbled%2C%20ok%0Aconst%20positiveMin%20%3D%20checkMin%28%20NaN%2C%205%20%29%20%2F%2F%20dissabled%2C%20wtf%3F%0A%0Aconst%20negativeMax%20%3D%20checkMax%28%20NaN%2C%20-5%20%29%20%2F%2F%20dissabled%2C%20wtf%3F%0Aconst%20positiveMax%20%3D%20checkMax%28%20NaN%2C%2010%20%29%20%2F%2F%20enabbled%2C%20ok/run=true), на диапазоне, который не захватывает 0, одна з кнопок будет выключена, а другая включена. Вообще, я думаю тут лучше обе дисейблить, а не пытаться считать от 0, то есть поменять логику на  `this.value() >= this.value_min()`.

2023-02-28 21:59 UTC, nin-jin commented
Пожалуй смёржу пока что, остальное не особо критично.

2023-02-28 21:59 UTC, merged

2023-03-02 06:41 UTC, wmakeev commented on number/number.view.ts
> +				!( ( this.value() || 0 ) <= this.value_min() )
Всё же, почему бы не дать возможность кликнуть по кнопке, если можно? Блокируя мы лишаем такой возможности. А то, что по умолчанию подразумеваем 0, так это самый частый случай.

Я бы только поправил, чтобы при нажатии на кнопку, пустота не интерпретировалась как 0, а просто подставлялся бы 0 и уже от него шел отчет.

2023-03-02 07:01 UTC, wmakeev commented on number/number.view.ts
> +				!( ( this.value() || 0 ) <= this.value_min() )
> Я бы только поправил, чтобы при нажатии на кнопку, пустота не интерпретировалась как 0, а просто подставлялся бы 0 и уже от него шел отчет.

Хотя это тоже спорно. Наверно надо от каких-то реальных случаев отталкиваться.

2023-03-02 10:44 UTC, nin-jin commented on number/number.view.ts
> +				!( ( this.value() || 0 ) <= this.value_min() )
Блокируя мы подсказываем, что меньше уже нельзя. Если не блокировать, то придётся объяснять, почему число при клике не меняется.