Добавление минимального JS-doc для основных компонентом $mol
hyoo-ru/mam_mol pull request #558
Opened 2023-03-18 16:04 UTC by Lyumih

Задача - сделать более быстрый переход на онлайн демо компонента и добавить минимальное описание, что он делает, где это возможно и уместно.

Структура:
1. Минимальное описание: Component that helps to upload files to server. 
2. Ссылка на демо:  @tutorial https://mol.hyoo.ru/#!section=demos/demo=mol_attach_demo

Пример:
```
namespace $.$$ {

	/**
	 * Component that helps to upload files to server.
	 * 
	 * @tutorial https://mol.hyoo.ru/#!section=demos/demo=mol_attach_demo
	 */
	export class $mol_attach extends $.$mol_attach {
```
Результат:
<img width="779" alt="image" src="https://user-images.githubusercontent.com/32732179/226117319-7a1e5e7e-9f1f-4b6f-ae31-6550ca1881e7.png">

2023-03-18 22:27 UTC, nin-jin requested changes
Токены типа $mol_hotkey в докстрингах вызывают подтягивание соответствующих зависимостей. Лучше без доллара в этом случае именовать или просто вставлять путь.

Ещё не стоит полную документацию в докстринги засовывать. Максимум короткий пример использования или ссылка на доку. Поддерживать несколько док никто не будет.

2023-03-19 09:19 UTC, nin-jin commented on state/arg/arg.node.ts
> +	 * $mol_state_arg.value( 'help' ) // null
3 не понятных примера вместо 1.

2023-03-19 09:20 UTC, nin-jin commented on state/arg/arg.web.ts
> +	 * $mol_state_arg.link({ xxx : '' , abc : 'hello' }) // '#foo=bar/xxx/abc=hello'
Куча не понятных примеров, да ещё и не у методов, а у класса.

2023-03-19 09:21 UTC, nin-jin commented on style/define/define.ts
> +	 * } )
Пример можно и по проще.

2023-03-19 09:23 UTC, nin-jin commented on view/view/view.ts
> +	 * The base class for all visual components. It provides the infrastructure for reactive lazy rendering, handling exceptions. By default it finds or creates a `div` without child node changing and a
Никаких дивов у нас нет. Думаю тут можно проще сказать, что создаёт дом элемент и реактивно его обновляет.

2023-03-19 09:24 UTC, nin-jin commented on assert/assert.ts
> +	 * $mol_assert_ok( 0 ) // Fails because Falsy
Два синтетических примера вместо 1 реалистичного типа: 2+2 = 2*2

2023-03-19 09:25 UTC, nin-jin commented on assert/assert.ts
> +	 * $mol_assert_ok( 1 ) // Fails because Truthy
Тут Math.random можно сравнить для примера.

2023-03-19 09:27 UTC, nin-jin commented on assert/assert.ts
> +	 * $mol_assert_fail( ()=>{ throw new Error( 'lol' ) } , RangeError ) // Fails because error isn't RangeError
Я бы убрал негативный пример, и не раскрывал содержание тестируемой функции - оно тут совсем не важно. А lol заменил на что-то правдоподобное, типа 'Parse error'.

2023-03-19 09:28 UTC, nin-jin commented on assert/assert.ts
> +	 * @see https://mol.hyoo.ru/#!section=docs/=9q9dv3_fgxjsf
Тут Math.random можно сравнить для примера.

2023-03-19 09:28 UTC, nin-jin commented on assert/assert.ts
> +	 * $mol_assert_equal( 1 , 1 , 2 ) // Fails because 1 !== 2
Два синтетических примера вместо 1 реалистичного типа: 2+2 = 2*2

2023-03-19 09:31 UTC, nin-jin commented on const/const.ts
> +	 * $mol_assert_equal( foo.bar() , foo.bar() )
Тестам в примере использования тоже не место.

2023-03-19 09:33 UTC, nin-jin commented on jsx/jsx.ts
> +	 * Can reuse an existing nodes by GUIDs when used inside [`$mol_jsx_attach`](https://github.com/hyoo-ru/mam_mol/tree/master/jsx/attach).
Зависимость.

2023-03-19 09:33 UTC, nin-jin commented on lights/lights.ts
> +	 * Switcher between light/dark themes (usually for `$mol_theme_auto` plugin).
Зависимсть, и так далее.

2023-03-19 17:12 UTC, Lyumih commented on assert/assert.ts
> +	 * @see https://mol.hyoo.ru/#!section=docs/=9q9dv3_fgxjsf
Взял пример из ридми

2023-03-19 17:20 UTC, Lyumih commented on state/arg/arg.node.ts
> +	 * $mol_state_arg.value( 'help' ) // null
убрал

2023-03-19 17:20 UTC, Lyumih commented on style/define/define.ts
> +	 * } )
сделал проще

2023-03-19 17:20 UTC, Lyumih commented on assert/assert.ts
> +	 * $mol_assert_fail( ()=>{ throw new Error( 'lol' ) } , RangeError ) // Fails because error isn't RangeError
Заменил lol на 'Parse error', убрал негативный пример

2023-03-19 17:21 UTC, Lyumih commented on assert/assert.ts
> +	 * $mol_assert_equal( 1 , 1 , 2 ) // Fails because 1 !== 2
Пример взят из readme и хорошо показывают то, что тут происходит

2023-03-19 17:21 UTC, Lyumih commented on const/const.ts
> +	 * $mol_assert_equal( foo.bar() , foo.bar() )
Убрал

2023-03-19 17:22 UTC, Lyumih commented on lights/lights.ts
> +	 * Switcher between light/dark themes (usually for `$mol_theme_auto` plugin).
Убрал тут и далее

2023-03-19 17:22 UTC, Lyumih commented on jsx/jsx.ts
> +	 * Can reuse an existing nodes by GUIDs when used inside [`$mol_jsx_attach`](https://github.com/hyoo-ru/mam_mol/tree/master/jsx/attach).
Убрал

2023-03-19 17:22 UTC, Lyumih commented on state/arg/arg.web.ts
> +	 * $mol_state_arg.link({ xxx : '' , abc : 'hello' }) // '#foo=bar/xxx/abc=hello'
Убрал

2023-03-19 17:23 UTC, Lyumih commented on const/const.ts
> +	 * $mol_assert_equal( foo.bar() , foo.bar['()'] )
Убрал и заменил пример из readme.md

2023-03-19 17:48 UTC, nin-jin commented on plugin/plugin.ts
> +	/** Plugin is component without its own DOM element, but instead uses the owner DOM element (like Angular's directives). */
Упоминания других фреймворков совсем не к месту.

2023-03-19 17:50 UTC, nin-jin commented on style/define/define.ts
> +	 * $mol_style_define( $mol_page , {
Зависимость.

2023-03-19 17:59 UTC, Lyumih commented on plugin/plugin.ts
> +	/** Plugin is component without its own DOM element, but instead uses the owner DOM element (like Angular's directives). */
Убрал

2023-03-19 18:02 UTC, Lyumih commented on style/define/define.ts
> +	 * $mol_style_define( $mol_page , {
Так это не зависимость, а @example код . Он не добавляет ссылки на документацию или что-то ещё
Они не кликабельны. 
Просто иначе это означать, что в JSDoc вообще нельзя упоминать $mol_component любые.

![telegram-cloud-photo-size-2-5242435067614185762-y](https://user-images.githubusercontent.com/32732179/226197321-5b728ac3-3907-4abb-bfa0-041b37ddaf06.jpg)

2023-03-19 19:12 UTC, nin-jin approved these changes

2023-03-19 19:20 UTC, merged