FIX Зависание обновления при ошибке в синаксисе view.tree
hyoo-ru/mam_mol pull request #609
Opened 2023-07-12 10:50 UTC by reatailret

2023-07-12 11:14 UTC, nin-jin commented on build/server/server.node.ts
> +				})
При первом исполнении уведомление не посылается. Нужно обратно перенести.

2023-07-12 11:15 UTC, nin-jin requested changes
...

2023-07-12 11:57 UTC, reatailret commented on build/server/server.node.ts
> +				})
Обновил.

2023-07-18 21:40 UTC, nin-jin approved these changes

2023-07-18 21:41 UTC, merged