$mol_form_draft: array support
hyoo-ru/mam_mol pull request #637
Opened 2023-09-28 15:36 UTC by zerkalica

2023-09-29 08:59 UTC, nin-jin commented on form/draft/draft.view.ts
> +		value_arr_str( field: string, next? : readonly string[] | null ) {
Давай без сокращений? `list_string()`, например.

2023-09-29 09:11 UTC, nin-jin commented on check/list/list.view.tree
> +	options_checked *
Давай options - это массив, а dictionary - словарь.

2023-09-29 09:14 UTC, nin-jin commented on check/list/list.view.ts
> +			if (next === undefined) return prev[id]
Давай null возвращать вместо undefined.

2023-09-29 19:54 UTC, nin-jin commented on form/draft/demo/demo.view.tree
> +			value_rec_bool*? => value_rec_bool*?
Ну а этих чего не переименовал?

2023-09-29 19:58 UTC, nin-jin commented on select/list/list.view.tree
> +			bubble_minimal_height <= bubble_minimal_height 30
Почему 30? Почему 200? Давай без констант наобум.

2023-09-29 20:00 UTC, zerkalica commented on select/list/list.view.tree
> +			bubble_minimal_height <= bubble_minimal_height 30
а что ставить то?

2023-09-29 20:02 UTC, nin-jin requested changes

2023-09-29 20:02 UTC, nin-jin commented on select/select.view.tree
> +					minimal_height <= bubble_minimal_height 30
Не стоит баловаться с этим, это потенциально ломает виртуализацию.

2023-09-29 20:02 UTC, nin-jin commented on select/list/list.view.tree
> +			bubble_minimal_height <= bubble_minimal_height 30
Ничего?

2023-09-29 20:03 UTC, zerkalica commented on select/list/list.view.tree
> +	filter_auto_clean true
не понял

2023-09-29 20:19 UTC, zerkalica commented on select/list/list.view.tree
> +			bubble_minimal_height <= bubble_minimal_height 30
тогда высоту то как минимальную сделать в строку? не хочу, что б попап в полоску скукоживался при ленивой загрузке

2023-09-29 20:22 UTC, nin-jin commented on select/list/list.view.tree
> +			bubble_minimal_height <= bubble_minimal_height 30
А  как она сейчас задаётся?

2023-09-29 20:22 UTC, nin-jin commented on select/list/list.view.tree
> +	filter_auto_clean true
Когда ставить true и false?

2023-09-29 20:37 UTC, zerkalica commented on select/list/list.view.tree
> +	filter_auto_clean true
true - когда надо, что б очищал фильтр при выборе элемента, как сейчас, false - отменить очистку

2023-09-29 20:40 UTC, zerkalica commented on select/list/list.view.tree
> +	filter_auto_clean true
можно назвать filter_clear_after_select

2023-09-30 15:36 UTC, nin-jin commented on select/list/list.view.tree
> +	filter_auto_clean true
Зачем вообще это свойство?

2023-09-30 15:36 UTC, nin-jin commented on select/list/list.view.tree
> +			bubble_minimal_height <= bubble_minimal_height 30
Вот может этот дефолт и увеличить?

2023-09-30 15:48 UTC, zerkalica commented on select/list/list.view.tree
> +	filter_auto_clean true
Сейчас, после выбора, попап переоткрывается, но фильтр очищается, приходится заново вбивать, искать и выбирать

2023-09-30 15:48 UTC, zerkalica commented on select/list/list.view.tree
> +	filter_auto_clean true
Это свойство отключает очистку, без него хрен перебьеш поведение

2023-09-30 16:06 UTC, nin-jin commented on select/list/list.view.tree
> +	filter_auto_clean true
Так может просто не закрывать попап?

2023-10-01 10:13 UTC, nin-jin commented on check/list/list.view.tree
> +	dictionary_checked *
Может просто `dictionary`, как в остальных местах?

2023-10-01 10:13 UTC, nin-jin commented on form/draft/demo/demo.view.tree
> +						pick_enabled true
Это же значение по умолчанию.

2023-10-01 10:13 UTC, nin-jin commented on form/draft/demo/demo.view.ts
> +		}
Это разве не поведение по умолчанию?

2023-10-01 10:13 UTC, nin-jin commented on select/list/list.view.tree
> +			filter_hint <= filter_hint @ \Filter..
А это переопределение точно нужно?

2023-10-01 10:16 UTC, zerkalica commented on select/list/list.view.tree
> +			filter_hint <= filter_hint @ \Filter..
да, по filter_pattern перестраивается ленивый словарь с вариантами

2023-10-01 10:16 UTC, zerkalica commented on form/draft/demo/demo.view.ts
> +		}
нет

2023-10-01 10:17 UTC, zerkalica commented on form/draft/demo/demo.view.tree
> +						pick_enabled true
нет, оно оверрайдится и вытягивается из dictionary, из-за этого лишний запрос при открытии формы

2023-10-01 10:20 UTC, nin-jin commented on form/draft/demo/demo.view.tree
> +						pick_enabled true
Если лишний запрос, значит где-то не хватает мемов.

2023-10-01 10:21 UTC, nin-jin commented on form/draft/demo/demo.view.ts
> +		}
![image](https://github.com/hyoo-ru/mam_mol/assets/442988/62146657-bf5c-40e1-a6a3-1514504e6c01)
В чём отличие?

2023-10-01 10:22 UTC, nin-jin commented on select/list/list.view.tree
> +			filter_hint <= filter_hint @ \Filter..
Тут про `filter_hint`.

2023-10-01 10:38 UTC, zerkalica commented on form/draft/demo/demo.view.tree
> +						pick_enabled true
дим, не выдумывай. лишний запрос из-за options_pickable https://github.com/hyoo-ru/mam_mol/blob/adf2555824262692d3762030d60cc8dfdee7c628/select/list/list.view.ts#L38

потому что select_list пытается выяснить, есть ли чего выбирать из словаря и включает +, если есть

Т.е. подразумевается, что без фильтра dictionary содержит ВСЕ айтемы, а фильтр их фильтрует

В случае ленивого dictionary это не так.

2023-10-01 10:40 UTC, zerkalica commented on form/draft/demo/demo.view.tree
> +						pick_enabled true
pick_enabled true в случае ленивого dictionary эту автоматизацию выключает нафиг, т.к. она не рабочая

2023-10-01 10:41 UTC, zerkalica commented on form/draft/demo/demo.view.ts
> +		}
в том что dictionary ленивый и начинает грузится, если ничего не выбрано

2023-10-01 10:42 UTC, zerkalica commented on select/list/list.view.tree
> +			filter_hint <= filter_hint @ \Filter..
как я его подниму, если надо читать и писать в него

2023-10-01 10:44 UTC, zerkalica commented on select/list/list.view.tree
> +			filter_hint <= filter_hint @ \Filter..
filter_hint нужен, ты ж в инпутах плейсхолдеры можешь кастомить, тут тоже самое, селект с фильтром пользователей, например, в инпуте так и надо напистать: "Фильтр пользователей" или пользователи, а не Фильтр..."

2023-10-01 10:50 UTC, nin-jin commented on form/draft/demo/demo.view.tree
> +						pick_enabled true
Демка драфта - не самое лучшее место демонстрации этой логики. Её бы перенести в `$mol_select_list_demo`, а тут оставить пример по проще.

2023-10-01 10:52 UTC, nin-jin commented on select/list/list.view.tree
> +			filter_hint <= filter_hint @ \Filter..
> как я его подниму, если надо читать и писать в него

`foo? => bar?`

2023-10-01 10:54 UTC, nin-jin commented on select/list/list.view.tree
> +			filter_hint <= filter_hint @ \Filter..
> filter_hint нужен, ты ж в инпутах плейсхолдеры можешь кастомить, тут тоже самое, селект с фильтром пользователей, например, в инпуте так и надо напистать: "Фильтр пользователей" или пользователи, а не Фильтр..."

Не надо писать лишних слов. Что ещё кроме пользователей можно фильтровать в списке пользователей?

2023-10-01 12:02 UTC, nin-jin approved these changes

2023-10-01 12:02 UTC, merged