$mol_view_tree2_to_dts tests and fixes
hyoo-ru/mam_mol pull request #646
Opened 2023-10-19 15:27 UTC by zerkalica

nullable

```view.tree
$mol_view_tree2_to_js_test_ex_simple_typed_null_foo $mol_object
	a null string|number
```

right chain

```
$mol_view_tree2_to_js_test_ex_right_hierarchy_foo $mol_object
	Indexed* $mol_view_tree2_to_js_test_ex_right_hierarchy_bar
		title? => indexed_title*?
		id <= indexed_id* 0
	prj $mol_view_tree2_to_js_test_ex_right_hierarchy_bar
		domain* => prj_domain*
			user => prj_user*
				id => prj_user_id*
```

typed dict values
```
$mol_view_tree2_to_js_test_ex_array_of_array_or_object_foo $mol_object
	complex /
		\1
		/
			true
		/
			\1
			21
		*number|string
			a 1
			str \some
```

generics

```
$mol_view_tree2_to_js_test_ex_array_constructor_tuple_foo $mol_object
	blobs /
		<= text_blob? $mol_view_tree2_to_js_test_ex_klass_tuple<string> /
			/string
				<= text \123
			* type \text/plain
```

2023-12-12 09:57 UTC, nin-jin requested changes

2023-12-12 09:57 UTC, nin-jin commented on view/tree2/to/js/test/js.array.test.ts
А зачем ты ассерты хранишь отдельно от тестируемых классов?

2023-12-12 09:57 UTC, nin-jin commented on view/tree2/to/js/test/run.ts
> +			?.[1].toLowerCase().replace(/[ .]/g, '_') ?? ''
Формат стека не детерминиован, очен хрупкий од.

2023-12-12 09:57 UTC, nin-jin commented on view/tree2/to/js/test/run.ts
> +		eval( js )
А в чём проблема просто собрать тестовый бандл с этими классами и ассертами, а не эвалить в рантайме?

2023-12-12 09:57 UTC, nin-jin commented on view/tree2/to/js/test/run.ts
> +	const str2js_dts = (function (this: $, data: string, url: string) {
dts похоже лишний.

2023-12-12 13:40 UTC, zerkalica commented on view/tree2/to/js/test/run.ts
> +		eval( js )
посмотри в тестах, негативные сценарии так не оттестить, именно надо что б падало

2023-12-16 20:43 UTC, zerkalica commented on build/build.node.ts
>  			return [ script ]
и какой же?

2023-12-16 20:46 UTC, zerkalica commented on image/image.view.ts
> +		natural_width( next?: null | number ) {
там ниже ресет тогда отвалится

```ts
		load() {
			this.natural_width( null )
			this.natural_height( null )
		}
```

2023-12-16 20:49 UTC, zerkalica commented on map/yandex/mark/mark.view.tree
> +	box $mol_vector_2d<$mol_vector_range<number>> /
Если ты про generic, то можно дефолт задать в классе $mol_vector2d, а так нет, в отличие от ts, в d.ts надо задавать точно

2023-12-16 20:50 UTC, zerkalica commented on sourcemap/dataurl.ts
> +	const end_comment = ' */'
мне точно нет

2023-12-16 20:52 UTC, zerkalica commented on sourcemap/sourcemap.ts
> +	export type $mol_sourcemap_mappings = $mol_sourcemap_line[]
не помню уже, я это просто выделил в отдельный файли, они и раньше были

Из какой библиотеки, кодека? он выпилится потом.

2023-12-16 20:56 UTC, zerkalica commented on tree/tree.ts
он 100% нигде не юзается, люди путаются, юзают его, стас например юзал где-то в недрах ide, лучше выпилить и забыть как страшный сон.

2023-12-16 20:58 UTC, zerkalica commented on sourcemap/sourcemap.ts
> +		return data.replace( /^\/\/#\s*sourceMappingURL=[^\n]*/mg , '' ) + '\n'
Какой второй?

2023-12-16 21:07 UTC, zerkalica commented on tree2/text/to/string/mapped/mapped.ts
> +		const chunk = this.$mol_sourcemap_dataurl_encode( map, type )
А куда его тогда это ж к tree не имеет отношения, просто функция энкода сорсмапа

2023-12-16 21:08 UTC, zerkalica commented on view/tree2/class/match.ts
> +	const class_regex = /^[$A-Z][$\w<>]+$/
Честно - не хочу, но иначе через d.ts тайпчек не сделать, поэтому базовые генерики разрешил, а что тут еще может быть? может не ограничится этим диапазоном?

2023-12-16 21:10 UTC, zerkalica commented on view/tree2/prop/parts.test.ts
> +			$mol_assert_equal(parts.next, '')
Думаю, не релевантно, ты депрекейтнул like   в пользу equal

2023-12-16 21:14 UTC, zerkalica commented on view/tree2/class/props.test.ts
> +			Text
что предлагаешь?

2023-12-16 21:16 UTC, zerkalica commented on view/tree2/prop/parts.test.ts
> +		},
По-моему легаси, раньше были именованные иднексы, потом стали дефолтные.
Нигде имена не использюется. тогда нужен тесткейс.

2023-12-16 21:17 UTC, zerkalica commented on view/tree2/to/dts/dts.ts
> +			name.data(`type ${ name.value.replace(/<.*>/g, '') }__${ this.$mol_guid() } = $mol_type_enforce<` ),
а как тогда вырезать генерики из типов?

2023-12-16 21:19 UTC, zerkalica commented on view/tree2/to/js/test/js.array.test.ts
не понял вопроса

2023-12-16 21:30 UTC, zerkalica commented on view/tree2/to/dts/dts.ts
> +				prop.data( 'id: any' + (next ? ', ' : '') ),
это ж dts, причем тут браузер?

2023-12-16 21:34 UTC, zerkalica commented on view/tree2/to/dts/dts.ts
> +			prop.data(name),
назвал пока channel_signature

2023-12-16 21:42 UTC, zerkalica commented on view/tree2/to/dts/dts.ts
> +		]
Что именно?
```ts
	const rt = $$.$mol_tree2_from_string(`
		ReturnType<#class['#name']>,
	`, 'rt' )
```

Маппинг похерится, input.data, name_of, не сильно это упростит, кода наоборот, станет больше

2023-12-16 21:53 UTC, zerkalica commented on view/tree2/to/dts/dts.ts
> +								: [ val.data( 'any' ) ]
не понятно про что ты.

пока сделал так:

```ts
							return kid?.type
								? [ kid.data(kid.type), val.data( ' | null' ) ]
								: [ val.data( 'any' ) ]
```

2023-12-16 21:54 UTC, zerkalica commented on view/tree2/to/dts/dts.ts
> +		]
где именно? если ты про struct, то красивее на каждой строчке, line их в одну строку смержит

2023-12-16 22:04 UTC, zerkalica commented on view/tree2/to/js/js.ts
> +		if( ! is_delegate && next ) addons.push( decorate() )
покажи на tree.hyoo.ru пример.

Я тут поддержал текущее поведение, левая часть бинда никогда не кэшится. decorate как раз и декорирует prop, который слева

2023-12-17 09:59 UTC, zerkalica commented on build/build.node.ts
>  			return [ script ]
тип string

2023-12-17 12:52 UTC, nin-jin commented on sourcemap/sourcemap.ts
> +		return data.replace( /^\/\/#\s*sourceMappingURL=[^\n]*/mg , '' ) + '\n'
```
//# ... 
/*# ... */
```

2023-12-17 12:53 UTC, nin-jin commented on tree2/text/to/string/mapped/mapped.ts
> +		const chunk = this.$mol_sourcemap_dataurl_encode( map, type )
Отрефакторить так, чтобы зависимость не тянулась без надобности.

2023-12-17 12:54 UTC, nin-jin commented on view/tree2/prop/parts.test.ts
> +		},
Дефолт как раз используется.

2023-12-17 12:55 UTC, nin-jin commented on view/tree2/to/dts/dts.ts
> +				prop.data( 'id: any' + (next ? ', ' : '') ),
dts ни при чём, да.

2023-12-17 12:57 UTC, nin-jin commented on view/tree2/to/dts/dts.ts
> +		]
tree шаблоны, а не какие попало. Они сохранят маппинг.

2023-12-17 13:01 UTC, nin-jin commented on view/tree2/to/dts/dts.ts
> +			name.data(`type ${ name.value.replace(/<.*>/g, '') }__${ this.$mol_guid() } = $mol_type_enforce<` ),
Завести отдельную переменную?

2023-12-17 13:03 UTC, nin-jin commented on view/tree2/to/js/js.ts
> +		if( ! is_delegate && next ) addons.push( decorate() )
```
foo? <= bar
```

foo надо мемоизировать, так как запись в него может происхдить напрямую.

2024-01-07 12:50 UTC, zerkalica commented on view/tree2/to/js/js.ts
> +		if( ! is_delegate && next ) addons.push( decorate() )
По мне, так не надо, если до сих пор не нужно было.  И так достаточно сложная логика, а так придется еще левые бинды в фабриках как-то учесть.

https://tree.hyoo.ru/#!source=%24my_app%20%24mol_page%0A%09kids%3F%20%3C%3D%20main_kids%20%2F%0A%09Info%20%24my_widget%0A%09%09kids%3F%20%3C%3D%20info_kids%20%2F%0A/pipeline=%24mol_tree2_from_string~%24mol_view_tree2_to_text~%24mol_tree2_text_to_string

2024-01-07 12:52 UTC, zerkalica commented on view/tree2/prop/parts.test.ts
> +		},
я не нашел примеров, по моему все-таки ты им пожертвовал

2024-01-07 12:54 UTC, zerkalica commented on view/tree2/to/dts/dts.ts
> +		]
Не вижу смысла в этих уровнях абстракции, ничего эти шаблоны тут не упрощают.

2024-02-11 12:15 UTC, merged