$mol_exec autokill if no output
hyoo-ru/mam_mol pull request #701
Opened 2024-10-06 10:32 UTC by zerkalica

2024-10-07 08:33 UTC, nin-jin requested changes

2024-10-07 08:33 UTC, nin-jin commented on exec/exec.node.test.ts
> +				const res = await $mol_wire_async(context_mock).$mol_exec('.', 'sleep', '10')
Под виндой нет такой команды.

2024-10-07 08:33 UTC, nin-jin commented on exec/exec.node.ts
> +	export let $mol_exec_deadline = 5000
Зачем это задавать глобальной константой?

2024-10-07 08:39 UTC, zerkalica commented on exec/exec.node.test.ts
> +				const res = await $mol_wire_async(context_mock).$mol_exec('.', 'sleep', '10')
тут это не важно, там мокается все

2024-10-07 08:41 UTC, zerkalica commented on exec/exec.node.ts
> +	export let $mol_exec_deadline = 5000
что бы оставить совместимой сигнатуру mol_exec и оставить возможность кастомить через контекст

если добавлять в аргументы, надо будет постоянно задавать, либо args делать не спредом, а массивом, deadline в конец сигнатуры mol_exec перемещать

2024-10-07 09:46 UTC, zerkalica commented on exec/exec.node.ts
> +	export let $mol_exec_deadline = 5000
выпилил, сделал mol_exec2

2024-10-07 09:53 UTC, nin-jin requested changes

2024-10-07 09:53 UTC, nin-jin commented on exec/exec.node.ts
> +		deadline?: number | null
timeout может?

2024-10-07 09:53 UTC, nin-jin commented on exec/exec.node.ts
> +	export function $mol_exec2(
Как-то многовато уже параметров (а потом потребуются ещё), может на объект переделать? Можно назвать $mol_run.

2024-10-07 09:53 UTC, nin-jin commented on exec/exec.node.ts
> +		return $mol_wire_sync(this).$mol_exec_async( dir, command, args ?? [], deadline )
Может лучше наоборот старый апи через новый реализовать?

2024-10-07 19:00 UTC, nin-jin commented on build/build.node.ts
> +			const repo = this.modMappedKids(path).find($mol_guard_defined)
А чего и тот гвард в метод не перенесешь?

2024-10-07 19:08 UTC, nin-jin commented on run/run.node.ts
> +		const reset = (std_chunk?: Buffer, error_chunk?: Buffer) => {
Почему reset называется?

2024-10-07 19:09 UTC, nin-jin commented on run/run.node.ts
> +				const stdout = Buffer.concat(std_data)
Вывод может дальше и не использоваться, а мы его зачем-то собираем.

2024-10-07 19:11 UTC, nin-jin approved these changes

2024-10-07 19:32 UTC, zerkalica commented on run/run.node.ts
> +		const reset = (std_chunk?: Buffer, error_chunk?: Buffer) => {
переименовал в add

2024-10-08 06:58 UTC, nin-jin approved these changes

2024-10-08 07:38 UTC, merged